app:
  name: "Sistem Pengelolaan Zakat"
  origin: "http://localhost:3000"
  smb:
    location: "smb://localhost:8080/share-folder-example"
    username: "root"
    password: "root"
spring:
  datasource:
    url: "jdbc:postgresql://localhost:5432/zakat"
    username: "admin"
    password: "123"
    driverClassName: org.postgresql.Driver
  rabbitmq:
    host: localhost
    username: guest
    password: guest
    port: 5672
  http:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
flyway:
  enabled: true
  baselineOnMigrate: true
  url: jdbc:postgresql://localhost:5432/zakat
  user: admin
  password: 123
  validateOnMigrate: false
server:
  port: 8081
sendgrid:
    api:
      key: "key"


